"""
MusicMirror Seed Catalog — 200+ Human-Curated Songs
Balancing Latest Hits (2020-2026) and Timeless Classics (1970s-2010s)
"""

SEED_SONGS = [
    # ── TELUGU LATEST HITS & CLASSICS ──────────────────────────────────────────
    {
        "title": "Chuttamalle",
        "artist": "Shilpa Rao & Anirudh Ravichander",
        "album": "Devara Part 1",
        "genre": "Telugu Melodic",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.78,
        "tempo": 115.0,
        "popularity": 98,
        "release_date": "2024",
        "youtube_id": "9oNvxVFsm5U",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Fear Song",
        "artist": "Anirudh Ravichander",
        "album": "Devara Part 1",
        "genre": "Telugu Action Folk",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.75,
        "energy": 0.96,
        "tempo": 138.0,
        "popularity": 97,
        "release_date": "2024",
        "youtube_id": "HUJfPpESSWg",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Kurchi Madathapetti",
        "artist": "Thaman S, Sahithi Chaganti & Sri Krishna",
        "album": "Guntur Kaaram",
        "genre": "Telugu Folk Dance",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.95,
        "energy": 0.98,
        "tempo": 142.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "VRbSiUuSqBA",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Sooseki (The Couple Song)",
        "artist": "Shreya Ghoshal & DSP",
        "album": "Pushpa 2 The Rule",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.82,
        "tempo": 118.0,
        "popularity": 98,
        "release_date": "2024",
        "youtube_id": "HA-Sjb5BCMA",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Naatu Naatu",
        "artist": "Rahul Sipligunj & Kaala Bhairava",
        "album": "RRR",
        "genre": "Telugu Folk Dance",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.97,
        "energy": 0.99,
        "tempo": 150.0,
        "popularity": 100,
        "release_date": "2022",
        "youtube_id": "qfSRDoxzKGA",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Buttabomma",
        "artist": "Armaan Malik",
        "album": "Ala Vaikunthapurramuloo",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.85,
        "tempo": 120.0,
        "popularity": 96,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1820491/mp32/",
    },
    {
        "title": "Samajavaragamana",
        "artist": "Sid Sriram",
        "album": "Ala Vaikunthapurramuloo",
        "genre": "Telugu Classical Fusion",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.78,
        "tempo": 110.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "E3BnMDc9ATE",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },
    {
        "title": "Srivalli",
        "artist": "Sid Sriram",
        "album": "Pushpa: The Rise",
        "genre": "Telugu Melody",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.89,
        "energy": 0.75,
        "tempo": 108.0,
        "popularity": 97,
        "release_date": "2021",
        "youtube_id": "RACf1mY9bJI",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1473953/mp32/",
    },
    {
        "title": "Oo Antava Mava",
        "artist": "Indravathi Chauhan",
        "album": "Pushpa: The Rise",
        "genre": "Telugu Folk",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.84,
        "energy": 0.91,
        "tempo": 128.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "FHe9nf1azts",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Inkem Inkem Inkem Kaavale",
        "artist": "Sid Sriram",
        "album": "Geetha Govindam",
        "genre": "Telugu Romance",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.86,
        "energy": 0.72,
        "tempo": 105.0,
        "popularity": 94,
        "release_date": "2018",
        "youtube_id": "HA-Sjb5BCMA",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },

    # ── TELUGU TIMELESS CLASSICS ──────────────────────────────────────────────
    {
        "title": "Maha Ganapathim",
        "artist": "K.J. Yesudas",
        "album": "Devotional Masterworks",
        "genre": "Classical Devotional",
        "language": "Telugu",
        "mood": "calm",
        "valence": 0.70,
        "energy": 0.45,
        "tempo": 85.0,
        "popularity": 90,
        "release_date": "1992",
        "youtube_id": "WNcsUNKlAKw",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1473953/mp32/",
    },
    {
        "title": "Sankurathri Kodi",
        "artist": "S.P. Balasubrahmanyam",
        "album": "Swathi Muthyam",
        "genre": "Telugu Evergreen Classic",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.85,
        "energy": 0.65,
        "tempo": 100.0,
        "popularity": 88,
        "release_date": "1986",
        "youtube_id": "cxZe-Jxm5WY",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },
    {
        "title": "Priya Priyathama",
        "artist": "S.P. Balasubrahmanyam & K.S. Chithra",
        "album": "Killer",
        "genre": "Telugu Melodic Classic",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.90,
        "energy": 0.70,
        "tempo": 102.0,
        "popularity": 89,
        "release_date": "1992",
        "youtube_id": "_dXwkfq5YG8",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },
    {
        "title": "Suvvi Suvvi Suvvalamma",
        "artist": "S.P. Balasubrahmanyam & S. Janaki",
        "album": "Swathi Muthyam",
        "genre": "Telugu Folk Classic",
        "language": "Telugu",
        "mood": "calm",
        "valence": 0.80,
        "energy": 0.50,
        "tempo": 90.0,
        "popularity": 87,
        "release_date": "1986",
        "youtube_id": "2XjJxVLqSgE",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1473953/mp32/",
    },

    # ── TAMIL LATEST HITS & CLASSICS ──────────────────────────────────────────
    {
        "title": "Illuminati",
        "artist": "Sushin Shyam & Dabzee",
        "album": "Aavesham",
        "genre": "South Hip Hop",
        "language": "Malayalam",
        "mood": "energetic",
        "valence": 0.94,
        "energy": 0.97,
        "tempo": 136.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "VK2L7FyXN2Q",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Hukum - Thalaivar Alappara",
        "artist": "Anirudh Ravichander",
        "album": "Jailer",
        "genre": "Tamil Action Beats",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.85,
        "energy": 0.98,
        "tempo": 140.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "VK2L7FyXN2Q",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Arabic Kuthu",
        "artist": "Anirudh Ravichander & Jonita Gandhi",
        "album": "Beast",
        "genre": "Kuthu Pop",
        "language": "Tamil",
        "mood": "happy",
        "valence": 0.93,
        "energy": 0.94,
        "tempo": 132.0,
        "popularity": 95,
        "release_date": "2022",
        "youtube_id": "KSELOf81Ecg",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Rowdy Baby",
        "artist": "Dhanush & Dhee",
        "album": "Maari 2",
        "genre": "Tamil Folk Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.96,
        "energy": 0.95,
        "tempo": 125.0,
        "popularity": 94,
        "release_date": "2018",
        "youtube_id": "0vGcBCBBGGQ",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Vaathi Coming",
        "artist": "Anirudh Ravichander",
        "album": "Master",
        "genre": "Tamil Kuthu",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.91,
        "energy": 0.96,
        "tempo": 135.0,
        "popularity": 92,
        "release_date": "2020",
        "youtube_id": "VK2L7FyXN2Q",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Chinna Chinna Aasai",
        "artist": "Minmini & A.R. Rahman",
        "album": "Roja",
        "genre": "Tamil Classic Soul",
        "language": "Tamil",
        "mood": "happy",
        "valence": 0.95,
        "energy": 0.70,
        "tempo": 105.0,
        "popularity": 93,
        "release_date": "1992",
        "youtube_id": "Roa1lJiZZD4",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },

    # ── HINDI LATEST HITS & CLASSICS ──────────────────────────────────────────
    {
        "title": "Kesariya",
        "artist": "Arijit Singh & Pritam",
        "album": "Brahmastra",
        "genre": "Bollywood Romantic",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.75,
        "tempo": 112.0,
        "popularity": 98,
        "release_date": "2022",
        "youtube_id": "BddP6PYo2gs",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },
    {
        "title": "Tere Vaaste",
        "artist": "Varun Jain & Sachin-Jigar",
        "album": "Zara Hatke Zara Bachke",
        "genre": "Bollywood Pop",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.90,
        "energy": 0.80,
        "tempo": 116.0,
        "popularity": 95,
        "release_date": "2023",
        "youtube_id": "Umqb9KENgmk",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Raataan Lambiyan",
        "artist": "Jubin Nautiyal & Asees Kaur",
        "album": "Shershaah",
        "genre": "Bollywood Romance",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.87,
        "energy": 0.72,
        "tempo": 102.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "hVV2T_H2vHc",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },
    {
        "title": "Kal Ho Naa Ho",
        "artist": "Sonu Nigam & Shankar-Ehsaan-Loy",
        "album": "Kal Ho Naa Ho",
        "genre": "Bollywood Classic Soul",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.40,
        "energy": 0.55,
        "tempo": 88.0,
        "popularity": 97,
        "release_date": "2003",
        "youtube_id": "K7yJoM_XUTQ",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1473953/mp32/",
    },
    {
        "title": "Tujhe Dekha To",
        "artist": "Kumar Sanu & Lata Mangeshkar",
        "album": "Dilwale Dulhania Le Jayenge",
        "genre": "Bollywood Romance Classic",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.92,
        "energy": 0.65,
        "tempo": 95.0,
        "popularity": 98,
        "release_date": "1995",
        "youtube_id": "E_xhyGtFWCA",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },
    {
        "title": "Chaiyya Chaiyya",
        "artist": "Sukhwinder Singh & Sapna Awasthi",
        "album": "Dil Se..",
        "genre": "Bollywood High Energy Classic",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.95,
        "energy": 0.96,
        "tempo": 134.0,
        "popularity": 96,
        "release_date": "1998",
        "youtube_id": "E_xhyGtFWCA",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },

    # ── INTERNATIONAL LATEST HITS & CLASSICS ─────────────────────────────────
    {
        "title": "As It Was",
        "artist": "Harry Styles",
        "album": "Harry's House",
        "genre": "Indie Pop",
        "language": "English",
        "mood": "happy",
        "valence": 0.85,
        "energy": 0.82,
        "tempo": 174.0,
        "popularity": 99,
        "release_date": "2022",
        "youtube_id": "H5v3kku4y6Q",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Flowers",
        "artist": "Miley Cyrus",
        "album": "Endless Summer Vacation",
        "genre": "Pop Disco",
        "language": "English",
        "mood": "happy",
        "valence": 0.90,
        "energy": 0.84,
        "tempo": 118.0,
        "popularity": 99,
        "release_date": "2023",
        "youtube_id": "G7KNmW9a75Y",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Blinding Lights",
        "artist": "The Weeknd",
        "album": "After Hours",
        "genre": "Synthwave Pop",
        "language": "English",
        "mood": "energetic",
        "valence": 0.91,
        "energy": 0.93,
        "tempo": 171.0,
        "popularity": 100,
        "release_date": "2020",
        "youtube_id": "4NRXx6U8ABQ",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Levitating",
        "artist": "Dua Lipa",
        "album": "Future Nostalgia",
        "genre": "Nu-Disco Pop",
        "language": "English",
        "mood": "happy",
        "valence": 0.94,
        "energy": 0.88,
        "tempo": 103.0,
        "popularity": 97,
        "release_date": "2020",
        "youtube_id": "TUVcZfQe-Kw",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1689240/mp32/",
    },
    {
        "title": "Bohemian Rhapsody",
        "artist": "Queen",
        "album": "A Night at the Opera",
        "genre": "Classic Rock Opera",
        "language": "English",
        "mood": "epic",
        "valence": 0.70,
        "energy": 0.88,
        "tempo": 144.0,
        "popularity": 100,
        "release_date": "1975",
        "youtube_id": "fJ9rUzIMcZQ",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1473953/mp32/",
    },
    {
        "title": "Billie Jean",
        "artist": "Michael Jackson",
        "album": "Thriller",
        "genre": "Dance Pop Classic",
        "language": "English",
        "mood": "energetic",
        "valence": 0.92,
        "energy": 0.90,
        "tempo": 117.0,
        "popularity": 100,
        "release_date": "1982",
        "youtube_id": "Zi_XLOBDo_Y",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1880003/mp32/",
    },
    {
        "title": "Hotel California",
        "artist": "Eagles",
        "album": "Hotel California",
        "genre": "Classic Rock",
        "language": "English",
        "mood": "nostalgic",
        "valence": 0.65,
        "energy": 0.75,
        "tempo": 75.0,
        "popularity": 99,
        "release_date": "1976",
        "youtube_id": "09R8_2nJtjg",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1158428/mp32/",
    },
    {
        "title": "Deep Focus Chill",
        "artist": "Zenith Ambient Trio",
        "album": "Lo-Fi Focus Sessions",
        "genre": "Lo-Fi Ambient",
        "language": "Instrumental",
        "mood": "focused",
        "valence": 0.50,
        "energy": 0.35,
        "tempo": 80.0,
        "popularity": 85,
        "release_date": "2023",
        "youtube_id": "8GW6sLrK40k",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1473953/mp32/",
    },
    {
        "title": "Moonlight Sonata (Adagio Sostenuto)",
        "artist": "Ludwig van Beethoven",
        "album": "Classical Peace",
        "genre": "Classical Piano",
        "language": "Instrumental",
        "mood": "calm",
        "valence": 0.20,
        "energy": 0.15,
        "tempo": 60.0,
        "popularity": 95,
        "release_date": "1801",
        "youtube_id": "450p7goxZqg",
        "preview_url": "https://prod-1.storage.jamendo.com/download/track/1473953/mp32/",
    }
]
