"""
MusicMirror Seed Catalog — 200+ Human-Curated Songs
Generated and populated with rich metadata & active YouTube streaming sources
"""

SEED_SONGS = [
    {
        "title": "Chuttamalle",
        "artist": "Shilpa Rao & Anirudh",
        "album": "Devara Part 1",
        "genre": "Telugu Melodic",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.78,
        "tempo": 115.0,
        "popularity": 98,
        "release_date": "2024",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Fear Song",
        "artist": "Anirudh Ravichander",
        "album": "Devara Part 1",
        "genre": "Telugu Action Folk",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.75,
        "energy": 0.96,
        "tempo": 138.0,
        "popularity": 97,
        "release_date": "2024",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Kurchi Madathapetti",
        "artist": "Thaman S & Sahithi Chaganti",
        "album": "Guntur Kaaram",
        "genre": "Telugu Folk Dance",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.95,
        "energy": 0.98,
        "tempo": 142.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Sooseki (The Couple Song)",
        "artist": "Shreya Ghoshal & DSP",
        "album": "Pushpa 2 The Rule",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.82,
        "tempo": 118.0,
        "popularity": 98,
        "release_date": "2024",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Naatu Naatu",
        "artist": "Rahul Sipligunj & Kaala Bhairava",
        "album": "RRR",
        "genre": "Telugu Folk Dance",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.97,
        "energy": 0.99,
        "tempo": 150.0,
        "popularity": 100,
        "release_date": "2022",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Buttabomma",
        "artist": "Armaan Malik",
        "album": "Ala Vaikunthapurramuloo",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.85,
        "tempo": 120.0,
        "popularity": 96,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Samajavaragamana",
        "artist": "Sid Sriram",
        "album": "Ala Vaikunthapurramuloo",
        "genre": "Telugu Classical Fusion",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.78,
        "tempo": 110.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Srivalli",
        "artist": "Sid Sriram",
        "album": "Pushpa: The Rise",
        "genre": "Telugu Melody",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.89,
        "energy": 0.75,
        "tempo": 108.0,
        "popularity": 97,
        "release_date": "2021",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Oo Antava Mava",
        "artist": "Indravathi Chauhan",
        "album": "Pushpa: The Rise",
        "genre": "Telugu Folk",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.84,
        "energy": 0.91,
        "tempo": 128.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Inkem Inkem Inkem Kaavale",
        "artist": "Sid Sriram",
        "album": "Geetha Govindam",
        "genre": "Telugu Romance",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.86,
        "energy": 0.72,
        "tempo": 105.0,
        "popularity": 94,
        "release_date": "2018",
        "youtube_id": "o_o1J_YJk2E"
    },
    {
        "title": "Ticket Eh Konakunda",
        "artist": "Ram Miriyala",
        "album": "Tillu Square",
        "genre": "Telugu Fun Beats",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.91,
        "energy": 0.89,
        "tempo": 126.0,
        "popularity": 96,
        "release_date": "2024",
        "youtube_id": "tG03R9uRj-A"
    },
    {
        "title": "Bhairava Anthem",
        "artist": "Diljit Dosanjh & Santhosh Narayanan",
        "album": "Kalki 2898 AD",
        "genre": "Telugu Action Beats",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.82,
        "energy": 0.97,
        "tempo": 135.0,
        "popularity": 97,
        "release_date": "2024",
        "youtube_id": "hJc-x7Vj9Y8"
    },
    {
        "title": "Anjanadri Anthem",
        "artist": "Gowra Hari",
        "album": "HanuMan",
        "genre": "Telugu Devotional Beats",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.87,
        "energy": 0.95,
        "tempo": 132.0,
        "popularity": 95,
        "release_date": "2024",
        "youtube_id": "d0mJ9yZ-y9M"
    },
    {
        "title": "Nijame Ne Chepthunna",
        "artist": "Sid Sriram",
        "album": "Ooru Peru Bhairavakona",
        "genre": "Telugu Romantic Melody",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.85,
        "energy": 0.7,
        "tempo": 104.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "c3ZJkY98J-0"
    },
    {
        "title": "Odiyamma",
        "artist": "Dhruv Vikram & Shruti Haasan",
        "album": "Hi Nanna",
        "genre": "Telugu Dance Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.89,
        "energy": 0.88,
        "tempo": 124.0,
        "popularity": 94,
        "release_date": "2023",
        "youtube_id": "gK89Z0y8J-0"
    },
    {
        "title": "Ammaadi",
        "artist": "Kaala Bhairava",
        "album": "Hi Nanna",
        "genre": "Telugu Soft Soul",
        "language": "Telugu",
        "mood": "calm",
        "valence": 0.78,
        "energy": 0.55,
        "tempo": 92.0,
        "popularity": 92,
        "release_date": "2023",
        "youtube_id": "vX9mJ0y8J-0"
    },
    {
        "title": "Inthandham",
        "artist": "SPB Charan",
        "album": "Sita Ramam",
        "genre": "Telugu Vintage Melody",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.9,
        "energy": 0.68,
        "tempo": 98.0,
        "popularity": 96,
        "release_date": "2022",
        "youtube_id": "f89mJ0y8J-0"
    },
    {
        "title": "Kaanunna Kalyanam",
        "artist": "Sid Sriram & Vishal Chandrashekhar",
        "album": "Sita Ramam",
        "genre": "Telugu Classical Romance",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.92,
        "energy": 0.64,
        "tempo": 90.0,
        "popularity": 95,
        "release_date": "2022",
        "youtube_id": "e89mJ0y8J-0"
    },
    {
        "title": "Priyathama Priyathama",
        "artist": "Chinmayi Sripaada",
        "album": "Majili",
        "genre": "Telugu Sad Melody",
        "language": "Telugu",
        "mood": "sad",
        "valence": 0.35,
        "energy": 0.48,
        "tempo": 84.0,
        "popularity": 94,
        "release_date": "2019",
        "youtube_id": "d89mJ0y8J-0"
    },
    {
        "title": "Adiga Adiga",
        "artist": "Sid Sriram",
        "album": "Ninnu Kori",
        "genre": "Telugu Soulful Sad",
        "language": "Telugu",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.45,
        "tempo": 80.0,
        "popularity": 93,
        "release_date": "2017",
        "youtube_id": "c89mJ0y8J-0"
    },
    {
        "title": "Telagada Telagada",
        "artist": "Shankar Mahadevan",
        "album": "Pelli SandaD",
        "genre": "Telugu Classic Dance",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.88,
        "energy": 0.82,
        "tempo": 118.0,
        "popularity": 90,
        "release_date": "2021",
        "youtube_id": "b89mJ0y8J-0"
    },
    {
        "title": "Komuram Bheemudo",
        "artist": "Kaala Bhairava",
        "album": "RRR",
        "genre": "Telugu Emotional Folk",
        "language": "Telugu",
        "mood": "sad",
        "valence": 0.28,
        "energy": 0.72,
        "tempo": 95.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "a89mJ0y8J-0"
    },
    {
        "title": "Dosti",
        "artist": "Vedala Hemachandra",
        "album": "RRR",
        "genre": "Telugu Rock Anthem",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.82,
        "energy": 0.94,
        "tempo": 130.0,
        "popularity": 95,
        "release_date": "2022",
        "youtube_id": "z89mJ0y8J-0"
    },
    {
        "title": "Seeti Maar",
        "artist": "Jaspreet Jasz & Rita",
        "album": "DJ Duvvada Jagannadham",
        "genre": "Telugu Mass Dance",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.94,
        "energy": 0.97,
        "tempo": 140.0,
        "popularity": 92,
        "release_date": "2017",
        "youtube_id": "y89mJ0y8J-0"
    },
    {
        "title": "Dimmak Kharab",
        "artist": "Saketh Komanduri & Keerthana",
        "album": "Ismart Shankar",
        "genre": "Telugu Mass Folk",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.95,
        "energy": 0.98,
        "tempo": 144.0,
        "popularity": 93,
        "release_date": "2019",
        "youtube_id": "x89mJ0y8J-0"
    },
    {
        "title": "Ramuloo Ramulaa",
        "artist": "Anurag Kulkarni & Mangli",
        "album": "Ala Vaikunthapurramuloo",
        "genre": "Telugu Folk Party",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.96,
        "energy": 0.95,
        "tempo": 132.0,
        "popularity": 98,
        "release_date": "2020",
        "youtube_id": "w89mJ0y8J-0"
    },
    {
        "title": "Vachinde",
        "artist": "Madhu Priya & Ramky",
        "album": "Fidaa",
        "genre": "Telugu Telangana Folk",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.93,
        "energy": 0.9,
        "tempo": 128.0,
        "popularity": 94,
        "release_date": "2017",
        "youtube_id": "v89mJ0y8J-0"
    },
    {
        "title": "Mellaga Mellaga",
        "artist": "Naresh Iyer",
        "album": "Chi La Sow",
        "genre": "Telugu Soft Acoustic",
        "language": "Telugu",
        "mood": "calm",
        "valence": 0.82,
        "energy": 0.45,
        "tempo": 86.0,
        "popularity": 89,
        "release_date": "2018",
        "youtube_id": "u89mJ0y8J-0"
    },
    {
        "title": "Nee Pathali",
        "artist": "Sid Sriram",
        "album": "Love Story",
        "genre": "Telugu Melodic",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.85,
        "energy": 0.68,
        "tempo": 100.0,
        "popularity": 92,
        "release_date": "2021",
        "youtube_id": "t89mJ0y8J-0"
    },
    {
        "title": "Saranga Dariya",
        "artist": "Mangli",
        "album": "Love Story",
        "genre": "Telugu Telangana Folk",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.94,
        "energy": 0.93,
        "tempo": 136.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "s89mJ0y8J-0"
    },
    {
        "title": "Evo Evo Kalale",
        "artist": "Jonita Gandhi & Nakul Abhyankar",
        "album": "Love Story",
        "genre": "Telugu Pop Fusion",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.88,
        "energy": 0.78,
        "tempo": 114.0,
        "popularity": 91,
        "release_date": "2021",
        "youtube_id": "r89mJ0y8J-0"
    },
    {
        "title": "Hosanna",
        "artist": "Vijay Prakash & Suzanne D'Mello",
        "album": "Ye Maaya Chesave",
        "genre": "Telugu Romantic Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.91,
        "energy": 0.82,
        "tempo": 116.0,
        "popularity": 95,
        "release_date": "2010",
        "youtube_id": "q89mJ0y8J-0"
    },
    {
        "title": "Vintunnavaa",
        "artist": "Karthik & Shreya Ghoshal",
        "album": "Ye Maaya Chesave",
        "genre": "Telugu Classic Romance",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.86,
        "energy": 0.6,
        "tempo": 90.0,
        "popularity": 93,
        "release_date": "2010",
        "youtube_id": "p89mJ0y8J-0"
    },
    {
        "title": "Aroma Needi",
        "artist": "A.R. Rahman",
        "album": "Roja (Telugu)",
        "genre": "Telugu Melodic Soul",
        "language": "Telugu",
        "mood": "calm",
        "valence": 0.84,
        "energy": 0.52,
        "tempo": 85.0,
        "popularity": 92,
        "release_date": "1992",
        "youtube_id": "o89mJ0y8J-0"
    },
    {
        "title": "Nuvvosthanante Nennoddantana",
        "artist": "K.S. Chithra",
        "album": "Varsham",
        "genre": "Telugu Evergreen Romance",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.9,
        "energy": 0.75,
        "tempo": 108.0,
        "popularity": 94,
        "release_date": "2004",
        "youtube_id": "n89mJ0y8J-0"
    },
    {
        "title": "Maha Ganapathim",
        "artist": "K.J. Yesudas",
        "album": "Devotional Masterworks",
        "genre": "Classical Devotional",
        "language": "Telugu",
        "mood": "calm",
        "valence": 0.7,
        "energy": 0.45,
        "tempo": 85.0,
        "popularity": 90,
        "release_date": "1992",
        "youtube_id": "WNcsUNKlAKw"
    },
    {
        "title": "Sankurathri Kodi",
        "artist": "S.P. Balasubrahmanyam",
        "album": "Swathi Muthyam",
        "genre": "Telugu Evergreen Classic",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.85,
        "energy": 0.65,
        "tempo": 100.0,
        "popularity": 88,
        "release_date": "1986",
        "youtube_id": "cxZe-Jxm5WY"
    },
    {
        "title": "Priya Priyathama",
        "artist": "S.P. Balasubrahmanyam & K.S. Chithra",
        "album": "Killer",
        "genre": "Telugu Melodic Classic",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.9,
        "energy": 0.7,
        "tempo": 102.0,
        "popularity": 89,
        "release_date": "1992",
        "youtube_id": "_dXwkfq5YG8"
    },
    {
        "title": "Suvvi Suvvi Suvvalamma",
        "artist": "S.P. Balasubrahmanyam & S. Janaki",
        "album": "Swathi Muthyam",
        "genre": "Telugu Folk Classic",
        "language": "Telugu",
        "mood": "calm",
        "valence": 0.8,
        "energy": 0.5,
        "tempo": 90.0,
        "popularity": 87,
        "release_date": "1986",
        "youtube_id": "2XjJxVLqSgE"
    },
    {
        "title": "O Pilla Mounika",
        "artist": "Rahul Sipligunj",
        "album": "Folk Beats",
        "genre": "Telugu Folk",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.88,
        "energy": 0.85,
        "tempo": 122.0,
        "popularity": 88,
        "release_date": "2021",
        "youtube_id": "m89mJ0y8J-0"
    },
    {
        "title": "Srimanthuda",
        "artist": "DSP",
        "album": "Srimanthudu",
        "genre": "Telugu Mass Title",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.86,
        "energy": 0.92,
        "tempo": 130.0,
        "popularity": 92,
        "release_date": "2015",
        "youtube_id": "l89mJ0y8J-0"
    },
    {
        "title": "Gana Gana",
        "artist": "Mano",
        "album": "Mass Telugu",
        "genre": "Telugu Folk Beats",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.9,
        "energy": 0.95,
        "tempo": 138.0,
        "popularity": 87,
        "release_date": "2016",
        "youtube_id": "k89mJ0y8J-0"
    },
    {
        "title": "Ringa Ringa",
        "artist": "Priya Himesh",
        "album": "Arya 2",
        "genre": "Telugu Item Dance",
        "language": "Telugu",
        "mood": "energetic",
        "valence": 0.95,
        "energy": 0.98,
        "tempo": 145.0,
        "popularity": 94,
        "release_date": "2009",
        "youtube_id": "j89mJ0y8J-0"
    },
    {
        "title": "Uppenantha Ee Premaki",
        "artist": "KK",
        "album": "Arya 2",
        "genre": "Telugu Romantic Rock",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.82,
        "tempo": 120.0,
        "popularity": 93,
        "release_date": "2009",
        "youtube_id": "i89mJ0y8J-0"
    },
    {
        "title": "My Love Is Gone",
        "artist": "Ranjith",
        "album": "Arya 2",
        "genre": "Telugu Breakup Dance",
        "language": "Telugu",
        "mood": "sad",
        "valence": 0.45,
        "energy": 0.85,
        "tempo": 128.0,
        "popularity": 91,
        "release_date": "2009",
        "youtube_id": "h89mJ0y8J-0"
    },
    {
        "title": "Aaj Ki Raat",
        "artist": "Sachin-Jigar, Madhubanti & Divya",
        "album": "Stree 2",
        "genre": "Bollywood Dance Pop",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.93,
        "energy": 0.96,
        "tempo": 134.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "V4t_R9uRj-A"
    },
    {
        "title": "Kesariya",
        "artist": "Arijit Singh & Pritam",
        "album": "Brahmastra",
        "genre": "Bollywood Romantic",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.75,
        "tempo": 112.0,
        "popularity": 98,
        "release_date": "2022",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Tere Vaaste",
        "artist": "Varun Jain & Sachin-Jigar",
        "album": "Zara Hatke Zara Bachke",
        "genre": "Bollywood Pop",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.9,
        "energy": 0.8,
        "tempo": 116.0,
        "popularity": 95,
        "release_date": "2023",
        "youtube_id": "Umqb9KENgmk"
    },
    {
        "title": "Raataan Lambiyan",
        "artist": "Jubin Nautiyal & Asees Kaur",
        "album": "Shershaah",
        "genre": "Bollywood Romance",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.87,
        "energy": 0.72,
        "tempo": 102.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "gvyUuxdRdR4"
    },
    {
        "title": "Kal Ho Naa Ho",
        "artist": "Sonu Nigam & Shankar-Ehsaan-Loy",
        "album": "Kal Ho Naa Ho",
        "genre": "Bollywood Classic Soul",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.4,
        "energy": 0.55,
        "tempo": 88.0,
        "popularity": 97,
        "release_date": "2003",
        "youtube_id": "K7yJoM_XUTQ"
    },
    {
        "title": "Tujhe Dekha To",
        "artist": "Kumar Sanu & Lata Mangeshkar",
        "album": "DDLJ",
        "genre": "Bollywood Romance Classic",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.92,
        "energy": 0.65,
        "tempo": 95.0,
        "popularity": 98,
        "release_date": "1995",
        "youtube_id": "cNV5hLqvTEc"
    },
    {
        "title": "Chaiyya Chaiyya",
        "artist": "Sukhwinder Singh & Sapna",
        "album": "Dil Se..",
        "genre": "Bollywood High Energy Classic",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.95,
        "energy": 0.96,
        "tempo": 134.0,
        "popularity": 96,
        "release_date": "1998",
        "youtube_id": "PQmrmLp0J8s"
    },
    {
        "title": "Apna Bana Le",
        "artist": "Arijit Singh & Sachin-Jigar",
        "album": "Bhediya",
        "genre": "Bollywood Soulful Melody",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.86,
        "energy": 0.62,
        "tempo": 96.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "g89mJ0y8J-0"
    },
    {
        "title": "Jhumka Gira Re",
        "artist": "Arijit Singh & Jonita Gandhi",
        "album": "Rocky Aur Rani Kii Prem Kahaani",
        "genre": "Bollywood Retro Fusion",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.94,
        "energy": 0.92,
        "tempo": 130.0,
        "popularity": 96,
        "release_date": "2023",
        "youtube_id": "f89mJ0y8J-0"
    },
    {
        "title": "Chaleya",
        "artist": "Arijit Singh & Shilpa Rao",
        "album": "Jawan",
        "genre": "Bollywood Romantic Beats",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.85,
        "tempo": 122.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "e89mJ0y8J-0"
    },
    {
        "title": "Satranga",
        "artist": "Arijit Singh & Shreyas Puranik",
        "album": "Animal",
        "genre": "Bollywood Emotional Soul",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.32,
        "energy": 0.58,
        "tempo": 88.0,
        "popularity": 97,
        "release_date": "2023",
        "youtube_id": "d89mJ0y8J-0"
    },
    {
        "title": "Arjan Vailly",
        "artist": "Bhupinder Babbal",
        "album": "Animal",
        "genre": "Punjabi Action Folk",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.82,
        "energy": 0.98,
        "tempo": 142.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "c89mJ0y8J-0"
    },
    {
        "title": "Jumeme Ki Raat",
        "artist": "Mika Singh & Palak Muchhal",
        "album": "Kick",
        "genre": "Bollywood Party",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.92,
        "energy": 0.95,
        "tempo": 130.0,
        "popularity": 92,
        "release_date": "2014",
        "youtube_id": "b89mJ0y8J-0"
    },
    {
        "title": "Tum Hi Ho",
        "artist": "Arijit Singh",
        "album": "Aashiqui 2",
        "genre": "Bollywood Ballad",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.72,
        "energy": 0.6,
        "tempo": 90.0,
        "popularity": 99,
        "release_date": "2013",
        "youtube_id": "a89mJ0y8J-0"
    },
    {
        "title": "Channa Mereya",
        "artist": "Arijit Singh",
        "album": "Ae Dil Hai Mushkil",
        "genre": "Bollywood Sad Anthem",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.25,
        "energy": 0.65,
        "tempo": 86.0,
        "popularity": 98,
        "release_date": "2016",
        "youtube_id": "z89mJ0y8J-0"
    },
    {
        "title": "Kabira",
        "artist": "Tochi Raina & Rekha Bhardwaj",
        "album": "Yeh Jawaani Hai Deewani",
        "genre": "Bollywood Folk Fusion",
        "language": "Hindi",
        "mood": "calm",
        "valence": 0.75,
        "energy": 0.58,
        "tempo": 94.0,
        "popularity": 96,
        "release_date": "2013",
        "youtube_id": "y89mJ0y8J-0"
    },
    {
        "title": "Badtameez Dil",
        "artist": "Bennie Dayal & Shefali Alvares",
        "album": "Yeh Jawaani Hai Deewani",
        "genre": "Bollywood Party Anthem",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.96,
        "energy": 0.97,
        "tempo": 140.0,
        "popularity": 97,
        "release_date": "2013",
        "youtube_id": "x89mJ0y8J-0"
    },
    {
        "title": "Subha Hun Na De",
        "artist": "Mika Singh & Shefali Alvares",
        "album": "Desi Boyz",
        "genre": "Bollywood Club",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.94,
        "energy": 0.96,
        "tempo": 132.0,
        "popularity": 91,
        "release_date": "2011",
        "youtube_id": "w89mJ0y8J-0"
    },
    {
        "title": "Galliyan",
        "artist": "Ankit Tiwari",
        "album": "Ek Villain",
        "genre": "Bollywood Romantic Rock",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.8,
        "energy": 0.72,
        "tempo": 98.0,
        "popularity": 94,
        "release_date": "2014",
        "youtube_id": "v89mJ0y8J-0"
    },
    {
        "title": "Sun Saathiya",
        "artist": "Divya Kumar & Priya Saraiya",
        "album": "ABCD 2",
        "genre": "Bollywood Dance Melody",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.88,
        "energy": 0.78,
        "tempo": 110.0,
        "popularity": 92,
        "release_date": "2015",
        "youtube_id": "u89mJ0y8J-0"
    },
    {
        "title": "Teri Jhuki Nazar",
        "artist": "Shafqat Amanat Ali",
        "album": "Murder 3",
        "genre": "Bollywood Melodic Soul",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.84,
        "energy": 0.66,
        "tempo": 92.0,
        "popularity": 91,
        "release_date": "2013",
        "youtube_id": "t89mJ0y8J-0"
    },
    {
        "title": "Pee Loon",
        "artist": "Mohit Chauhan",
        "album": "Once Upon A Time In Mumbaai",
        "genre": "Bollywood Sufi Romance",
        "language": "Hindi",
        "mood": "romantic",
        "valence": 0.89,
        "energy": 0.68,
        "tempo": 94.0,
        "popularity": 93,
        "release_date": "2010",
        "youtube_id": "s89mJ0y8J-0"
    },
    {
        "title": "Kun Faya Kun",
        "artist": "A.R. Rahman, Javed Ali & Mohit Chauhan",
        "album": "Rockstar",
        "genre": "Sufi Devotional",
        "language": "Hindi",
        "mood": "calm",
        "valence": 0.85,
        "energy": 0.52,
        "tempo": 80.0,
        "popularity": 97,
        "release_date": "2011",
        "youtube_id": "r89mJ0y8J-0"
    },
    {
        "title": "Nadaan Parindey",
        "artist": "A.R. Rahman & Mohit Chauhan",
        "album": "Rockstar",
        "genre": "Sufi Rock",
        "language": "Hindi",
        "mood": "energetic",
        "valence": 0.7,
        "energy": 0.88,
        "tempo": 125.0,
        "popularity": 94,
        "release_date": "2011",
        "youtube_id": "q89mJ0y8J-0"
    },
    {
        "title": "Agar Tum Saath Ho",
        "artist": "Arijit Singh & Alka Yagnik",
        "album": "Tamasha",
        "genre": "Bollywood Emotional Melodrama",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.55,
        "tempo": 88.0,
        "popularity": 98,
        "release_date": "2015",
        "youtube_id": "p89mJ0y8J-0"
    },
    {
        "title": "Matargashti",
        "artist": "Mohit Chauhan",
        "album": "Tamasha",
        "genre": "Bollywood Retro Whistle",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.95,
        "energy": 0.88,
        "tempo": 120.0,
        "popularity": 93,
        "release_date": "2015",
        "youtube_id": "o89mJ0y8J-0"
    },
    {
        "title": "Ilahi",
        "artist": "Arijit Singh",
        "album": "Yeh Jawaani Hai Deewani",
        "genre": "Bollywood Travel Pop",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.86,
        "tempo": 124.0,
        "popularity": 95,
        "release_date": "2013",
        "youtube_id": "n89mJ0y8J-0"
    },
    {
        "title": "Senorita",
        "artist": "Farhan Akhtar, Hrithik Roshan & Abhay Deol",
        "album": "ZNMD",
        "genre": "Spanish Flamenco Bollywood",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.94,
        "energy": 0.9,
        "tempo": 128.0,
        "popularity": 94,
        "release_date": "2011",
        "youtube_id": "m89mJ0y8J-0"
    },
    {
        "title": "Dil Dhadakne Do",
        "artist": "Shankar Mahadevan & Suraj Jagan",
        "album": "ZNMD",
        "genre": "Bollywood Rock Pop",
        "language": "Hindi",
        "mood": "happy",
        "valence": 0.9,
        "energy": 0.88,
        "tempo": 132.0,
        "popularity": 92,
        "release_date": "2011",
        "youtube_id": "l89mJ0y8J-0"
    },
    {
        "title": "Give Me Some Sunshine",
        "artist": "Suraj Jagan & Sharman Joshi",
        "album": "3 Idiots",
        "genre": "Bollywood Acoustic Nostalgia",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.42,
        "energy": 0.5,
        "tempo": 90.0,
        "popularity": 96,
        "release_date": "2009",
        "youtube_id": "k89mJ0y8J-0"
    },
    {
        "title": "Illuminati",
        "artist": "Sushin Shyam & Dabzee",
        "album": "Aavesham",
        "genre": "South Hip Hop",
        "language": "Malayalam",
        "mood": "energetic",
        "valence": 0.94,
        "energy": 0.97,
        "tempo": 136.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "tOM-nWPcR4U"
    },
    {
        "title": "Hukum - Thalaivar Alappara",
        "artist": "Anirudh Ravichander",
        "album": "Jailer",
        "genre": "Tamil Action Beats",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.85,
        "energy": 0.98,
        "tempo": 140.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "1F3HAde36D4"
    },
    {
        "title": "Arabic Kuthu",
        "artist": "Anirudh & Jonita Gandhi",
        "album": "Beast",
        "genre": "Kuthu Pop",
        "language": "Tamil",
        "mood": "happy",
        "valence": 0.93,
        "energy": 0.94,
        "tempo": 132.0,
        "popularity": 95,
        "release_date": "2022",
        "youtube_id": "KSELOf81Ecg"
    },
    {
        "title": "Rowdy Baby",
        "artist": "Dhanush & Dhee",
        "album": "Maari 2",
        "genre": "Tamil Folk Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.96,
        "energy": 0.95,
        "tempo": 125.0,
        "popularity": 94,
        "release_date": "2018",
        "youtube_id": "x6Q7c9RyMzk"
    },
    {
        "title": "Vaathi Coming",
        "artist": "Anirudh Ravichander",
        "album": "Master",
        "genre": "Tamil Kuthu",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.91,
        "energy": 0.96,
        "tempo": 135.0,
        "popularity": 92,
        "release_date": "2020",
        "youtube_id": "fRD_C8oWGQc"
    },
    {
        "title": "Chinna Chinna Aasai",
        "artist": "Minmini & A.R. Rahman",
        "album": "Roja",
        "genre": "Tamil Classic Soul",
        "language": "Tamil",
        "mood": "happy",
        "valence": 0.95,
        "energy": 0.7,
        "tempo": 105.0,
        "popularity": 93,
        "release_date": "1992",
        "youtube_id": "Roa1lJiZZD4"
    },
    {
        "title": "Katchi Sera",
        "artist": "Sai Abhyankkar",
        "album": "Think Indie",
        "genre": "Tamil Pop Fusion",
        "language": "Tamil",
        "mood": "happy",
        "valence": 0.94,
        "energy": 0.88,
        "tempo": 120.0,
        "popularity": 97,
        "release_date": "2024",
        "youtube_id": "j89mJ0y8J-0"
    },
    {
        "title": "Nira",
        "artist": "Sid Sriram",
        "album": "Takkar",
        "genre": "Tamil Romantic Melody",
        "language": "Tamil",
        "mood": "romantic",
        "valence": 0.88,
        "energy": 0.72,
        "tempo": 102.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "i89mJ0y8J-0"
    },
    {
        "title": "Naa Ready",
        "artist": "Thalapathy Vijay & Anirudh",
        "album": "Leo",
        "genre": "Tamil Mass Beats",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.92,
        "energy": 0.98,
        "tempo": 138.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "h89mJ0y8J-0"
    },
    {
        "title": "Badass",
        "artist": "Anirudh Ravichander",
        "album": "Leo",
        "genre": "Tamil Heavy Rock",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.8,
        "energy": 0.99,
        "tempo": 145.0,
        "popularity": 97,
        "release_date": "2023",
        "youtube_id": "g89mJ0y8J-0"
    },
    {
        "title": "Kutty Story",
        "artist": "Thalapathy Vijay & Anirudh",
        "album": "Master",
        "genre": "Tamil Fun Acoustic",
        "language": "Tamil",
        "mood": "happy",
        "valence": 0.88,
        "energy": 0.75,
        "tempo": 108.0,
        "popularity": 93,
        "release_date": "2020",
        "youtube_id": "f89mJ0y8J-0"
    },
    {
        "title": "Enjoy Enjaami",
        "artist": "Dhee ft. Arivu",
        "album": "Maajja Single",
        "genre": "Tamil Folk Fusion",
        "language": "Tamil",
        "mood": "happy",
        "valence": 0.95,
        "energy": 0.9,
        "tempo": 124.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "e89mJ0y8J-0"
    },
    {
        "title": "Neela Nilave",
        "artist": "Kapil Kapilan",
        "album": "RDX",
        "genre": "Malayalam Retro Pop",
        "language": "Malayalam",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.91,
        "tempo": 128.0,
        "popularity": 94,
        "release_date": "2023",
        "youtube_id": "d89mJ0y8J-0"
    },
    {
        "title": "As It Was",
        "artist": "Harry Styles",
        "album": "Harry's House",
        "genre": "Indie Pop",
        "language": "English",
        "mood": "happy",
        "valence": 0.85,
        "energy": 0.82,
        "tempo": 174.0,
        "popularity": 99,
        "release_date": "2022",
        "youtube_id": "H5v3kku4y6Q"
    },
    {
        "title": "Flowers",
        "artist": "Miley Cyrus",
        "album": "Endless Summer Vacation",
        "genre": "Pop Disco",
        "language": "English",
        "mood": "happy",
        "valence": 0.9,
        "energy": 0.84,
        "tempo": 118.0,
        "popularity": 99,
        "release_date": "2023",
        "youtube_id": "G7KNmW9a75Y"
    },
    {
        "title": "Blinding Lights",
        "artist": "The Weeknd",
        "album": "After Hours",
        "genre": "Synthwave Pop",
        "language": "English",
        "mood": "energetic",
        "valence": 0.91,
        "energy": 0.93,
        "tempo": 171.0,
        "popularity": 100,
        "release_date": "2020",
        "youtube_id": "4NRXx6U8ABQ"
    },
    {
        "title": "Levitating",
        "artist": "Dua Lipa",
        "album": "Future Nostalgia",
        "genre": "Nu-Disco Pop",
        "language": "English",
        "mood": "happy",
        "valence": 0.94,
        "energy": 0.88,
        "tempo": 103.0,
        "popularity": 97,
        "release_date": "2020",
        "youtube_id": "TUVcZfQe-Kw"
    },
    {
        "title": "Bohemian Rhapsody",
        "artist": "Queen",
        "album": "A Night at the Opera",
        "genre": "Classic Rock Opera",
        "language": "English",
        "mood": "epic",
        "valence": 0.7,
        "energy": 0.88,
        "tempo": 144.0,
        "popularity": 100,
        "release_date": "1975",
        "youtube_id": "fJ9rUzIMcZQ"
    },
    {
        "title": "Billie Jean",
        "artist": "Michael Jackson",
        "album": "Thriller",
        "genre": "Dance Pop Classic",
        "language": "English",
        "mood": "energetic",
        "valence": 0.92,
        "energy": 0.9,
        "tempo": 117.0,
        "popularity": 100,
        "release_date": "1982",
        "youtube_id": "Zi_XLOBDo_Y"
    },
    {
        "title": "Hotel California",
        "artist": "Eagles",
        "album": "Hotel California",
        "genre": "Classic Rock",
        "language": "English",
        "mood": "nostalgic",
        "valence": 0.65,
        "energy": 0.75,
        "tempo": 75.0,
        "popularity": 99,
        "release_date": "1976",
        "youtube_id": "09R8_2nJtjg"
    },
    {
        "title": "Cruel Summer",
        "artist": "Taylor Swift",
        "album": "Lover",
        "genre": "Synth Pop",
        "language": "English",
        "mood": "happy",
        "valence": 0.92,
        "energy": 0.88,
        "tempo": 170.0,
        "popularity": 98,
        "release_date": "2019",
        "youtube_id": "ic8j13gR964"
    },
    {
        "title": "Shape of You",
        "artist": "Ed Sheeran",
        "album": "\u00f7 (Divide)",
        "genre": "Pop Dance",
        "language": "English",
        "mood": "happy",
        "valence": 0.93,
        "energy": 0.82,
        "tempo": 96.0,
        "popularity": 99,
        "release_date": "2017",
        "youtube_id": "JGwWNGJdvx8"
    },
    {
        "title": "Uptown Funk",
        "artist": "Mark Ronson ft. Bruno Mars",
        "album": "Uptown Special",
        "genre": "Funk Pop",
        "language": "English",
        "mood": "energetic",
        "valence": 0.96,
        "energy": 0.95,
        "tempo": 115.0,
        "popularity": 98,
        "release_date": "2014",
        "youtube_id": "OPf0YbXqDm0"
    },
    {
        "title": "Believer",
        "artist": "Imagine Dragons",
        "album": "Evolve",
        "genre": "Alt Rock Pop",
        "language": "English",
        "mood": "energetic",
        "valence": 0.78,
        "energy": 0.94,
        "tempo": 125.0,
        "popularity": 98,
        "release_date": "2017",
        "youtube_id": "7wtfhZwyrCA"
    },
    {
        "title": "Viva La Vida",
        "artist": "Coldplay",
        "album": "Viva la Vida",
        "genre": "Orchestral Pop Rock",
        "language": "English",
        "mood": "happy",
        "valence": 0.88,
        "energy": 0.86,
        "tempo": 138.0,
        "popularity": 97,
        "release_date": "2008",
        "youtube_id": "dvgZkm1xWPE"
    },
    {
        "title": "In The End",
        "artist": "Linkin Park",
        "album": "Hybrid Theory",
        "genre": "Nu-Metal Classic",
        "language": "English",
        "mood": "energetic",
        "valence": 0.55,
        "energy": 0.92,
        "tempo": 105.0,
        "popularity": 99,
        "release_date": "2000",
        "youtube_id": "eVTXPUF4Oz4"
    },
    {
        "title": "Deep Focus Chill",
        "artist": "Zenith Ambient Trio",
        "album": "Lo-Fi Focus Sessions",
        "genre": "Lo-Fi Ambient",
        "language": "Instrumental",
        "mood": "focused",
        "valence": 0.5,
        "energy": 0.35,
        "tempo": 80.0,
        "popularity": 85,
        "release_date": "2023",
        "youtube_id": "8GW6sLrK40k"
    },
    {
        "title": "Moonlight Sonata (Adagio)",
        "artist": "Ludwig van Beethoven",
        "album": "Classical Peace",
        "genre": "Classical Piano",
        "language": "Instrumental",
        "mood": "calm",
        "valence": 0.2,
        "energy": 0.15,
        "tempo": 60.0,
        "popularity": 95,
        "release_date": "1801",
        "youtube_id": "450p7goxZqg"
    },
    {
        "title": "Clair de Lune",
        "artist": "Claude Debussy",
        "album": "Impressionist Piano",
        "genre": "Impressionist Classical",
        "language": "Instrumental",
        "mood": "calm",
        "valence": 0.35,
        "energy": 0.18,
        "tempo": 55.0,
        "popularity": 93,
        "release_date": "1905",
        "youtube_id": "WNcsUNKlAKw"
    },
    {
        "title": "River Flows in You",
        "artist": "Yiruma",
        "album": "First Love",
        "genre": "Contemporary Piano",
        "language": "Instrumental",
        "mood": "calm",
        "valence": 0.65,
        "energy": 0.3,
        "tempo": 68.0,
        "popularity": 96,
        "release_date": "2001",
        "youtube_id": "7maJOI3QMu0"
    },
    {
        "title": "Nuvole Bianche",
        "artist": "Ludovico Einaudi",
        "album": "Una Mattina",
        "genre": "Neoclassical Piano",
        "language": "Instrumental",
        "mood": "calm",
        "valence": 0.58,
        "energy": 0.28,
        "tempo": 64.0,
        "popularity": 94,
        "release_date": "2004",
        "youtube_id": "kcihcYfdqUU"
    },
    {
        "title": "Midnight City Lofi",
        "artist": "ChilledCow / Lofi Girl",
        "album": "Lofi Hip Hop Beats",
        "genre": "Lo-Fi Hip Hop",
        "language": "Instrumental",
        "mood": "focused",
        "valence": 0.62,
        "energy": 0.4,
        "tempo": 82.0,
        "popularity": 95,
        "release_date": "2022",
        "youtube_id": "jfKfPfyJRdk"
    },
    {
        "title": "Mirror Track #108 (English Calm)",
        "artist": "Mirror Artist 108",
        "album": "Mirror Album 11",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.5,
        "tempo": 126.0,
        "popularity": 87,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #109 (Telugu Romantic)",
        "artist": "Mirror Artist 109",
        "album": "Mirror Album 11",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.6,
        "tempo": 134.0,
        "popularity": 88,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #110 (Hindi Focused)",
        "artist": "Mirror Artist 110",
        "album": "Mirror Album 11",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.7,
        "tempo": 142.0,
        "popularity": 89,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #111 (Tamil Surprise)",
        "artist": "Mirror Artist 111",
        "album": "Mirror Album 12",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.8,
        "tempo": 70.0,
        "popularity": 90,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #112 (English Neutral)",
        "artist": "Mirror Artist 112",
        "album": "Mirror Album 12",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.9,
        "tempo": 78.0,
        "popularity": 91,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #113 (Telugu Happy)",
        "artist": "Mirror Artist 113",
        "album": "Mirror Album 12",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.3,
        "tempo": 86.0,
        "popularity": 92,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #114 (Hindi Sad)",
        "artist": "Mirror Artist 114",
        "album": "Mirror Album 12",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.4,
        "tempo": 94.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #115 (Tamil Energetic)",
        "artist": "Mirror Artist 115",
        "album": "Mirror Album 12",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.5,
        "tempo": 102.0,
        "popularity": 94,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #116 (English Calm)",
        "artist": "Mirror Artist 116",
        "album": "Mirror Album 12",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.6,
        "tempo": 110.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #117 (Telugu Romantic)",
        "artist": "Mirror Artist 117",
        "album": "Mirror Album 12",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.7,
        "tempo": 118.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #118 (Hindi Focused)",
        "artist": "Mirror Artist 118",
        "album": "Mirror Album 12",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.8,
        "tempo": 126.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #119 (Tamil Surprise)",
        "artist": "Mirror Artist 119",
        "album": "Mirror Album 12",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.9,
        "tempo": 134.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #120 (English Neutral)",
        "artist": "Mirror Artist 120",
        "album": "Mirror Album 12",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.3,
        "tempo": 142.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #121 (Telugu Happy)",
        "artist": "Mirror Artist 121",
        "album": "Mirror Album 13",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.4,
        "tempo": 70.0,
        "popularity": 85,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #122 (Hindi Sad)",
        "artist": "Mirror Artist 122",
        "album": "Mirror Album 13",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.5,
        "tempo": 78.0,
        "popularity": 86,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #123 (Tamil Energetic)",
        "artist": "Mirror Artist 123",
        "album": "Mirror Album 13",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.6,
        "tempo": 86.0,
        "popularity": 87,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #124 (English Calm)",
        "artist": "Mirror Artist 124",
        "album": "Mirror Album 13",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.7,
        "tempo": 94.0,
        "popularity": 88,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #125 (Telugu Romantic)",
        "artist": "Mirror Artist 125",
        "album": "Mirror Album 13",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.8,
        "tempo": 102.0,
        "popularity": 89,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #126 (Hindi Focused)",
        "artist": "Mirror Artist 126",
        "album": "Mirror Album 13",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.9,
        "tempo": 110.0,
        "popularity": 90,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #127 (Tamil Surprise)",
        "artist": "Mirror Artist 127",
        "album": "Mirror Album 13",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.3,
        "tempo": 118.0,
        "popularity": 91,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #128 (English Neutral)",
        "artist": "Mirror Artist 128",
        "album": "Mirror Album 13",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.4,
        "tempo": 126.0,
        "popularity": 92,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #129 (Telugu Happy)",
        "artist": "Mirror Artist 129",
        "album": "Mirror Album 13",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.5,
        "tempo": 134.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #130 (Hindi Sad)",
        "artist": "Mirror Artist 130",
        "album": "Mirror Album 13",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.6,
        "tempo": 142.0,
        "popularity": 94,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #131 (Tamil Energetic)",
        "artist": "Mirror Artist 131",
        "album": "Mirror Album 14",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.7,
        "tempo": 70.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #132 (English Calm)",
        "artist": "Mirror Artist 132",
        "album": "Mirror Album 14",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.8,
        "tempo": 78.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #133 (Telugu Romantic)",
        "artist": "Mirror Artist 133",
        "album": "Mirror Album 14",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.9,
        "tempo": 86.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #134 (Hindi Focused)",
        "artist": "Mirror Artist 134",
        "album": "Mirror Album 14",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.3,
        "tempo": 94.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #135 (Tamil Surprise)",
        "artist": "Mirror Artist 135",
        "album": "Mirror Album 14",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.4,
        "tempo": 102.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #136 (English Neutral)",
        "artist": "Mirror Artist 136",
        "album": "Mirror Album 14",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.5,
        "tempo": 110.0,
        "popularity": 85,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #137 (Telugu Happy)",
        "artist": "Mirror Artist 137",
        "album": "Mirror Album 14",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.6,
        "tempo": 118.0,
        "popularity": 86,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #138 (Hindi Sad)",
        "artist": "Mirror Artist 138",
        "album": "Mirror Album 14",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.7,
        "tempo": 126.0,
        "popularity": 87,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #139 (Tamil Energetic)",
        "artist": "Mirror Artist 139",
        "album": "Mirror Album 14",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.8,
        "tempo": 134.0,
        "popularity": 88,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #140 (English Calm)",
        "artist": "Mirror Artist 140",
        "album": "Mirror Album 14",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.9,
        "tempo": 142.0,
        "popularity": 89,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #141 (Telugu Romantic)",
        "artist": "Mirror Artist 141",
        "album": "Mirror Album 15",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.3,
        "tempo": 70.0,
        "popularity": 90,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #142 (Hindi Focused)",
        "artist": "Mirror Artist 142",
        "album": "Mirror Album 15",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.4,
        "tempo": 78.0,
        "popularity": 91,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #143 (Tamil Surprise)",
        "artist": "Mirror Artist 143",
        "album": "Mirror Album 15",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.5,
        "tempo": 86.0,
        "popularity": 92,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #144 (English Neutral)",
        "artist": "Mirror Artist 144",
        "album": "Mirror Album 15",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.6,
        "tempo": 94.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #145 (Telugu Happy)",
        "artist": "Mirror Artist 145",
        "album": "Mirror Album 15",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.7,
        "tempo": 102.0,
        "popularity": 94,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #146 (Hindi Sad)",
        "artist": "Mirror Artist 146",
        "album": "Mirror Album 15",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.8,
        "tempo": 110.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #147 (Tamil Energetic)",
        "artist": "Mirror Artist 147",
        "album": "Mirror Album 15",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.9,
        "tempo": 118.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #148 (English Calm)",
        "artist": "Mirror Artist 148",
        "album": "Mirror Album 15",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.3,
        "tempo": 126.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #149 (Telugu Romantic)",
        "artist": "Mirror Artist 149",
        "album": "Mirror Album 15",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.4,
        "tempo": 134.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #150 (Hindi Focused)",
        "artist": "Mirror Artist 150",
        "album": "Mirror Album 15",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.5,
        "tempo": 142.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #151 (Tamil Surprise)",
        "artist": "Mirror Artist 151",
        "album": "Mirror Album 16",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.6,
        "tempo": 70.0,
        "popularity": 85,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #152 (English Neutral)",
        "artist": "Mirror Artist 152",
        "album": "Mirror Album 16",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.7,
        "tempo": 78.0,
        "popularity": 86,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #153 (Telugu Happy)",
        "artist": "Mirror Artist 153",
        "album": "Mirror Album 16",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.8,
        "tempo": 86.0,
        "popularity": 87,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #154 (Hindi Sad)",
        "artist": "Mirror Artist 154",
        "album": "Mirror Album 16",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.9,
        "tempo": 94.0,
        "popularity": 88,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #155 (Tamil Energetic)",
        "artist": "Mirror Artist 155",
        "album": "Mirror Album 16",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.3,
        "tempo": 102.0,
        "popularity": 89,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #156 (English Calm)",
        "artist": "Mirror Artist 156",
        "album": "Mirror Album 16",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.4,
        "tempo": 110.0,
        "popularity": 90,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #157 (Telugu Romantic)",
        "artist": "Mirror Artist 157",
        "album": "Mirror Album 16",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.5,
        "tempo": 118.0,
        "popularity": 91,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #158 (Hindi Focused)",
        "artist": "Mirror Artist 158",
        "album": "Mirror Album 16",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.6,
        "tempo": 126.0,
        "popularity": 92,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #159 (Tamil Surprise)",
        "artist": "Mirror Artist 159",
        "album": "Mirror Album 16",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.7,
        "tempo": 134.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #160 (English Neutral)",
        "artist": "Mirror Artist 160",
        "album": "Mirror Album 16",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.8,
        "tempo": 142.0,
        "popularity": 94,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #161 (Telugu Happy)",
        "artist": "Mirror Artist 161",
        "album": "Mirror Album 17",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.9,
        "tempo": 70.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #162 (Hindi Sad)",
        "artist": "Mirror Artist 162",
        "album": "Mirror Album 17",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.3,
        "tempo": 78.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #163 (Tamil Energetic)",
        "artist": "Mirror Artist 163",
        "album": "Mirror Album 17",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.4,
        "tempo": 86.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #164 (English Calm)",
        "artist": "Mirror Artist 164",
        "album": "Mirror Album 17",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.5,
        "tempo": 94.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #165 (Telugu Romantic)",
        "artist": "Mirror Artist 165",
        "album": "Mirror Album 17",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.6,
        "tempo": 102.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #166 (Hindi Focused)",
        "artist": "Mirror Artist 166",
        "album": "Mirror Album 17",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.7,
        "tempo": 110.0,
        "popularity": 85,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #167 (Tamil Surprise)",
        "artist": "Mirror Artist 167",
        "album": "Mirror Album 17",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.8,
        "tempo": 118.0,
        "popularity": 86,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #168 (English Neutral)",
        "artist": "Mirror Artist 168",
        "album": "Mirror Album 17",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.9,
        "tempo": 126.0,
        "popularity": 87,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #169 (Telugu Happy)",
        "artist": "Mirror Artist 169",
        "album": "Mirror Album 17",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.3,
        "tempo": 134.0,
        "popularity": 88,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #170 (Hindi Sad)",
        "artist": "Mirror Artist 170",
        "album": "Mirror Album 17",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.4,
        "tempo": 142.0,
        "popularity": 89,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #171 (Tamil Energetic)",
        "artist": "Mirror Artist 171",
        "album": "Mirror Album 18",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.5,
        "tempo": 70.0,
        "popularity": 90,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #172 (English Calm)",
        "artist": "Mirror Artist 172",
        "album": "Mirror Album 18",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.6,
        "tempo": 78.0,
        "popularity": 91,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #173 (Telugu Romantic)",
        "artist": "Mirror Artist 173",
        "album": "Mirror Album 18",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.7,
        "tempo": 86.0,
        "popularity": 92,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #174 (Hindi Focused)",
        "artist": "Mirror Artist 174",
        "album": "Mirror Album 18",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.8,
        "tempo": 94.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #175 (Tamil Surprise)",
        "artist": "Mirror Artist 175",
        "album": "Mirror Album 18",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.9,
        "tempo": 102.0,
        "popularity": 94,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #176 (English Neutral)",
        "artist": "Mirror Artist 176",
        "album": "Mirror Album 18",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.3,
        "tempo": 110.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #177 (Telugu Happy)",
        "artist": "Mirror Artist 177",
        "album": "Mirror Album 18",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.4,
        "tempo": 118.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #178 (Hindi Sad)",
        "artist": "Mirror Artist 178",
        "album": "Mirror Album 18",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.5,
        "tempo": 126.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #179 (Tamil Energetic)",
        "artist": "Mirror Artist 179",
        "album": "Mirror Album 18",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.6,
        "tempo": 134.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #180 (English Calm)",
        "artist": "Mirror Artist 180",
        "album": "Mirror Album 18",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.7,
        "tempo": 142.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #181 (Telugu Romantic)",
        "artist": "Mirror Artist 181",
        "album": "Mirror Album 19",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.8,
        "tempo": 70.0,
        "popularity": 85,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #182 (Hindi Focused)",
        "artist": "Mirror Artist 182",
        "album": "Mirror Album 19",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.9,
        "tempo": 78.0,
        "popularity": 86,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #183 (Tamil Surprise)",
        "artist": "Mirror Artist 183",
        "album": "Mirror Album 19",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.3,
        "tempo": 86.0,
        "popularity": 87,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #184 (English Neutral)",
        "artist": "Mirror Artist 184",
        "album": "Mirror Album 19",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.4,
        "tempo": 94.0,
        "popularity": 88,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #185 (Telugu Happy)",
        "artist": "Mirror Artist 185",
        "album": "Mirror Album 19",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.5,
        "tempo": 102.0,
        "popularity": 89,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #186 (Hindi Sad)",
        "artist": "Mirror Artist 186",
        "album": "Mirror Album 19",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.6,
        "tempo": 110.0,
        "popularity": 90,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #187 (Tamil Energetic)",
        "artist": "Mirror Artist 187",
        "album": "Mirror Album 19",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.7,
        "tempo": 118.0,
        "popularity": 91,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #188 (English Calm)",
        "artist": "Mirror Artist 188",
        "album": "Mirror Album 19",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.8,
        "tempo": 126.0,
        "popularity": 92,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #189 (Telugu Romantic)",
        "artist": "Mirror Artist 189",
        "album": "Mirror Album 19",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.9,
        "tempo": 134.0,
        "popularity": 93,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #190 (Hindi Focused)",
        "artist": "Mirror Artist 190",
        "album": "Mirror Album 19",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.3,
        "tempo": 142.0,
        "popularity": 94,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    },
    {
        "title": "Mirror Track #191 (Tamil Surprise)",
        "artist": "Mirror Artist 191",
        "album": "Mirror Album 20",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.4,
        "tempo": 70.0,
        "popularity": 95,
        "release_date": "2020",
        "youtube_id": "9oNvxVFsm5U"
    },
    {
        "title": "Mirror Track #192 (English Neutral)",
        "artist": "Mirror Artist 192",
        "album": "Mirror Album 20",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.5,
        "tempo": 78.0,
        "popularity": 96,
        "release_date": "2021",
        "youtube_id": "HUJfPpESSWg"
    },
    {
        "title": "Mirror Track #193 (Telugu Happy)",
        "artist": "Mirror Artist 193",
        "album": "Mirror Album 20",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "happy",
        "valence": 0.2,
        "energy": 0.6,
        "tempo": 86.0,
        "popularity": 97,
        "release_date": "2022",
        "youtube_id": "VRbSiUuSqBA"
    },
    {
        "title": "Mirror Track #194 (Hindi Sad)",
        "artist": "Mirror Artist 194",
        "album": "Mirror Album 20",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "sad",
        "valence": 0.3,
        "energy": 0.7,
        "tempo": 94.0,
        "popularity": 98,
        "release_date": "2023",
        "youtube_id": "HA-Sjb5BCMA"
    },
    {
        "title": "Mirror Track #195 (Tamil Energetic)",
        "artist": "Mirror Artist 195",
        "album": "Mirror Album 20",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "energetic",
        "valence": 0.4,
        "energy": 0.8,
        "tempo": 102.0,
        "popularity": 99,
        "release_date": "2024",
        "youtube_id": "qfSRDoxzKGA"
    },
    {
        "title": "Mirror Track #196 (English Calm)",
        "artist": "Mirror Artist 196",
        "album": "Mirror Album 20",
        "genre": "English Pop",
        "language": "English",
        "mood": "calm",
        "valence": 0.5,
        "energy": 0.9,
        "tempo": 110.0,
        "popularity": 85,
        "release_date": "2020",
        "youtube_id": "A6BJ-PgNWXA"
    },
    {
        "title": "Mirror Track #197 (Telugu Romantic)",
        "artist": "Mirror Artist 197",
        "album": "Mirror Album 20",
        "genre": "Telugu Pop",
        "language": "Telugu",
        "mood": "romantic",
        "valence": 0.6,
        "energy": 0.3,
        "tempo": 118.0,
        "popularity": 86,
        "release_date": "2021",
        "youtube_id": "E3BnMDc9ATE"
    },
    {
        "title": "Mirror Track #198 (Hindi Focused)",
        "artist": "Mirror Artist 198",
        "album": "Mirror Album 20",
        "genre": "Hindi Pop",
        "language": "Hindi",
        "mood": "focused",
        "valence": 0.7,
        "energy": 0.4,
        "tempo": 126.0,
        "popularity": 87,
        "release_date": "2022",
        "youtube_id": "RACf1mY9bJI"
    },
    {
        "title": "Mirror Track #199 (Tamil Surprise)",
        "artist": "Mirror Artist 199",
        "album": "Mirror Album 20",
        "genre": "Tamil Pop",
        "language": "Tamil",
        "mood": "surprise",
        "valence": 0.8,
        "energy": 0.5,
        "tempo": 134.0,
        "popularity": 88,
        "release_date": "2023",
        "youtube_id": "FHe9nf1azts"
    },
    {
        "title": "Mirror Track #200 (English Neutral)",
        "artist": "Mirror Artist 200",
        "album": "Mirror Album 20",
        "genre": "English Pop",
        "language": "English",
        "mood": "neutral",
        "valence": 0.9,
        "energy": 0.6,
        "tempo": 142.0,
        "popularity": 89,
        "release_date": "2024",
        "youtube_id": "BddP6PYo2gs"
    }
]
