/**
 * Music Mirror — Data Classification System (Spec §14)
 *
 * Classify data before implementing storage or transmission.
 * Do not classify data merely by its name — classify according to actual usage.
 *
 * Rule: Apply minimum necessary protection and retention to each category.
 *
 * Classification hierarchy (most → least sensitive):
 *   SENSITIVE_CONTEXT > PERSONAL_DATA > USER_DATA > DEVICE_DATA >
 *   DERIVED_DATA > PROVIDER_DATA > TEMPORARY_DATA > INTERNAL > PUBLIC
 */

// ---------------------------------------------------------------------------
// Classification Enum
// ---------------------------------------------------------------------------

export const DataClass = {
  /**
   * Raw biometric or sensor data.
   * Examples: raw camera frames, raw audio input, precise geolocation.
   * Handling: Do not store. Process transiently. Do not transmit without explicit consent.
   */
  SENSITIVE_CONTEXT: 'SENSITIVE_CONTEXT',

  /**
   * Data that can directly identify or profile a specific person.
   * Examples: user ID, email, name, IP address.
   * Handling: Store only when necessary. Encrypt at rest. Minimize retention.
   */
  PERSONAL_DATA: 'PERSONAL_DATA',

  /**
   * Data generated by user activity that is not directly identifying on its own,
   * but could become identifying in combination.
   * Examples: listening history, search history, playlists, feedback, favorites.
   * Handling: Retain only for functional purpose. User must be able to delete it.
   */
  USER_DATA: 'USER_DATA',

  /**
   * Data about the user's device or browser environment.
   * Examples: user agent, screen resolution, hardware capabilities.
   * Handling: Do not retain unnecessarily. Do not transmit to third parties.
   */
  DEVICE_DATA: 'DEVICE_DATA',

  /**
   * Data derived by inference from other data.
   * Examples: inferred emotion from camera, recommended tracks, mood classification.
   * Handling: Treat derived personal inference with same care as its source data.
   * If source was SENSITIVE_CONTEXT, derived inference may be PERSONAL_DATA.
   */
  DERIVED_DATA: 'DERIVED_DATA',

  /**
   * Data received from external providers that MM stores or processes.
   * Examples: YouTube video metadata, backend catalog data.
   * Handling: Do not trust blindly. Validate before use. Retain bounded by TTL.
   */
  PROVIDER_DATA: 'PROVIDER_DATA',

  /**
   * Data that exists only for the duration of an operation or session.
   * Examples: camera frames during inference, search query in flight, audio chunks.
   * Handling: Discard when operation completes. Must not persist to storage.
   */
  TEMPORARY_DATA: 'TEMPORARY_DATA',

  /**
   * Internal system data not tied to user identity.
   * Examples: cache metadata, performance metrics, error codes, server version.
   * Handling: May be stored for operational purposes. Do not include user identity.
   */
  INTERNAL: 'INTERNAL',

  /**
   * Publicly available data with no sensitivity.
   * Examples: track title, artist name, YouTube video ID.
   * Handling: No special restrictions. May be cached and transmitted freely.
   */
  PUBLIC: 'PUBLIC',
} as const;

export type DataClass = typeof DataClass[keyof typeof DataClass];

// ---------------------------------------------------------------------------
// Classification Map — MM-specific data fields
// ---------------------------------------------------------------------------

/**
 * Classification of all known data fields in MM.
 *
 * This map must be updated whenever a new data field is introduced.
 * Use this as the privacy/data-flow audit reference (spec §31).
 */
export const MM_DATA_CLASSIFICATIONS: Readonly<Record<string, DataClass>> = {
  // Camera
  'camera.raw_frame':              DataClass.SENSITIVE_CONTEXT,
  'camera.landmark_positions':     DataClass.SENSITIVE_CONTEXT,
  'camera.pixel_data':             DataClass.SENSITIVE_CONTEXT,
  'camera.inferred_emotion':       DataClass.DERIVED_DATA,
  'camera.confidence_score':       DataClass.DERIVED_DATA,
  'camera.inference_latency_ms':   DataClass.INTERNAL,

  // User identity
  'user.id':                       DataClass.PERSONAL_DATA,
  'user.email':                    DataClass.PERSONAL_DATA,
  'user.name':                     DataClass.PERSONAL_DATA,

  // User preferences
  'user.preferred_genres':         DataClass.USER_DATA,
  'user.preferred_languages':      DataClass.USER_DATA,
  'user.preferred_artists':        DataClass.USER_DATA,
  'user.preferred_moods':          DataClass.USER_DATA,
  'user.music_goal':               DataClass.USER_DATA,
  'user.volume':                   DataClass.USER_DATA,
  'user.auto_play':                DataClass.USER_DATA,
  'user.theme':                    DataClass.USER_DATA,

  // Listening activity
  'user.listening_history':        DataClass.USER_DATA,
  'user.search_history':           DataClass.USER_DATA,
  'user.queue_history':            DataClass.USER_DATA,
  'user.playback_events':          DataClass.USER_DATA,
  'user.feedback_ratings':         DataClass.USER_DATA,

  // Emotion session
  'session.active_emotion_id':     DataClass.TEMPORARY_DATA,
  'session.mirror_policy':         DataClass.TEMPORARY_DATA,
  'session.user_note':             DataClass.TEMPORARY_DATA,
  'session.facial_detection':      DataClass.DERIVED_DATA,

  // Tracks (public music metadata)
  'track.title':                   DataClass.PUBLIC,
  'track.artist':                  DataClass.PUBLIC,
  'track.album':                   DataClass.PUBLIC,
  'track.duration_seconds':        DataClass.PUBLIC,
  'track.youtube_id':              DataClass.PUBLIC,
  'track.thumbnail_url':           DataClass.PUBLIC,
  'track.valence':                 DataClass.PUBLIC,
  'track.energy':                  DataClass.PUBLIC,
  'track.tempo':                   DataClass.PUBLIC,
  'track.genre':                   DataClass.PUBLIC,
  'track.language':                DataClass.PUBLIC,

  // Candidate/discovery pool
  'discovery.search_query':        DataClass.TEMPORARY_DATA,
  'discovery.candidate_pool':      DataClass.TEMPORARY_DATA,
  'discovery.cache_entry':         DataClass.PROVIDER_DATA,
  'discovery.cache_key':           DataClass.INTERNAL,
  'cache.offline_audio_blob':      DataClass.PROVIDER_DATA,
  'cache.offline_track_metadata':  DataClass.PROVIDER_DATA,

  // Audio DSP & Spectral telemetry
  'audio.rms_energy':              DataClass.INTERNAL,
  'audio.spectral_centroid':       DataClass.INTERNAL,
  'audio.spectral_flatness':       DataClass.INTERNAL,
  'audio.bands':                   DataClass.INTERNAL,
  'audio.validation_result':       DataClass.INTERNAL,

  // Playback state
  'playback.current_track':        DataClass.TEMPORARY_DATA,
  'playback.position_seconds':     DataClass.TEMPORARY_DATA,
  'playback.volume_percent':       DataClass.USER_DATA,
  'playback.is_muted':             DataClass.USER_DATA,
  'playback.status':               DataClass.TEMPORARY_DATA,
  'playback.error_code':           DataClass.INTERNAL,

  // System / diagnostics
  'system.health_status':          DataClass.INTERNAL,
  'system.backend_latency_ms':     DataClass.INTERNAL,
  'system.provider_id':            DataClass.INTERNAL,
  'system.app_version':            DataClass.PUBLIC,
  'system.error_message':          DataClass.INTERNAL,
  'system.log_entry':              DataClass.INTERNAL,

  // Consent records
  'consent.purpose':               DataClass.INTERNAL,
  'consent.decision':              DataClass.INTERNAL,
  'consent.timestamp':             DataClass.INTERNAL,
  'consent.policy_version':        DataClass.INTERNAL,
};

// ---------------------------------------------------------------------------
// Retention Policies
// ---------------------------------------------------------------------------

export interface RetentionPolicy {
  /** Human-readable description of when this data is discarded */
  policy: string;
  /** Storage mechanism (or 'none' if not persisted) */
  storage: 'none' | 'memory' | 'sessionStorage' | 'localStorage' | 'indexedDB' | 'server';
  /** Maximum age in seconds before data must be discarded. -1 means user-controlled. */
  maxAgeSeconds: number;
}

/**
 * Retention policies per DataClass.
 * These define the maximum retention for each classification category.
 */
export const RETENTION_POLICIES: Readonly<Record<DataClass, RetentionPolicy>> = {
  [DataClass.SENSITIVE_CONTEXT]: {
    policy: 'Discard immediately after transient processing. Must not be stored.',
    storage: 'none',
    maxAgeSeconds: 0,
  },
  [DataClass.PERSONAL_DATA]: {
    policy: 'Retain only as long as the account relationship exists or user deletes it.',
    storage: 'server',
    maxAgeSeconds: -1, // User-controlled
  },
  [DataClass.USER_DATA]: {
    policy: 'Retain until user explicitly deletes it or resets account.',
    storage: 'server',
    maxAgeSeconds: -1, // User-controlled
  },
  [DataClass.DEVICE_DATA]: {
    policy: 'Retain for the duration of the session. Discard on session end.',
    storage: 'memory',
    maxAgeSeconds: 86400, // 24h max
  },
  [DataClass.DERIVED_DATA]: {
    policy: 'Treat same as source data class. If derived from SENSITIVE_CONTEXT, discard after operation.',
    storage: 'memory',
    maxAgeSeconds: 3600, // 1h max in-session
  },
  [DataClass.PROVIDER_DATA]: {
    policy: 'Cache with bounded TTL. Do not retain raw provider data indefinitely.',
    storage: 'memory',
    maxAgeSeconds: 3600, // 1h TTL for discovery cache
  },
  [DataClass.TEMPORARY_DATA]: {
    policy: 'Discard when the operation that produced it completes.',
    storage: 'memory',
    maxAgeSeconds: 300, // 5 min max
  },
  [DataClass.INTERNAL]: {
    policy: 'May be retained for operational monitoring. Must not contain user identity.',
    storage: 'memory',
    maxAgeSeconds: 86400,
  },
  [DataClass.PUBLIC]: {
    policy: 'No sensitivity restrictions. May be cached as needed.',
    storage: 'memory',
    maxAgeSeconds: 86400,
  },
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Classify a known MM data field.
 * Returns null if the field is not registered in the classification map.
 *
 * Spec §14: "Do not classify data merely by its name."
 * If a field is not in this map, it needs a classification review before use.
 */
export function classifyField(fieldKey: string): DataClass | null {
  return MM_DATA_CLASSIFICATIONS[fieldKey] ?? null;
}

/**
 * Get the retention policy for a data class.
 */
export function getRetentionPolicy(dataClass: DataClass): RetentionPolicy {
  return RETENTION_POLICIES[dataClass];
}

/**
 * Returns true if a data class must NOT be stored to persistent storage.
 */
export function mustNotPersist(dataClass: DataClass): boolean {
  return dataClass === DataClass.SENSITIVE_CONTEXT || dataClass === DataClass.TEMPORARY_DATA;
}

/**
 * Returns true if a data class requires explicit user consent before transmission.
 */
export function requiresConsentForTransmission(dataClass: DataClass): boolean {
  return (
    dataClass === DataClass.SENSITIVE_CONTEXT ||
    dataClass === DataClass.PERSONAL_DATA ||
    dataClass === DataClass.USER_DATA
  );
}

/**
 * Returns all fields classified at a given level.
 * Useful for privacy audits (spec §34).
 */
export function getFieldsByClass(dataClass: DataClass): string[] {
  return Object.entries(MM_DATA_CLASSIFICATIONS)
    .filter(([, cls]) => cls === dataClass)
    .map(([key]) => key);
}
